name: Deploy Frontend to AWS EB

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    - name: Build Nuxt
      run: |
        cd frontend
        npm run build

    - name: Package frontend
      run: |
        cd frontend
        zip -r ../frontend.zip .output package.json package-lock.json Procfile

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: portfolio-frontend
        environment_name: portfolio-frontend-env
        version_label: frontend-${{ github.sha }}
        region: ap-northeast-1
        deployment_package: frontend.zip
