name: Deploy Backend to AWS EB

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Install AWS EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          APPLICATION_NAME: portfolio-backend
          ENVIRONMENT_NAME: Portfolio-backend-prod
        run: |
          export PATH=$PATH:~/.local/bin
          cd backend
          
          # バージョンラベルにコミットIDを使用
          VERSION_LABEL="backend-${GITHUB_SHA}"
          echo "Deploying version: $VERSION_LABEL"

          # war ファイルを zip にまとめてデプロイ
          zip deploy.zip target/*.war
          eb deploy --staged --label "$VERSION_LABEL"
