name: Deploy Frontend to AWS EB

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Nuxt app
        run: |
          cd frontend
          npm run build

      - name: Install AWS EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          export PATH=$PATH:~/.local/bin
          cd frontend
          VERSION_LABEL="frontend-${GITHUB_SHA}"
          echo "Deploying version: $VERSION_LABEL"

          # 初期化（最初だけ必要）
          eb init ${{ secrets.EB_APP_NAME_FRONTEND }} --platform "Node.js 18 running on 64bit Amazon Linux 2" --region $AWS_REGION
          eb use ${{ secrets.EB_ENV_NAME_FRONTEND }}

          # SSR 実行に必要なファイルをまとめて zip 化
          zip -r deploy.zip .output package.json package-lock.json Procfile
          eb deploy --staged --label "$VERSION_LABEL"
